import streamlit as st
import os
import markdown
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent

st.set_page_config(page_title="AI Study Buddy", page_icon="🇧🇩", layout="centered")

st.title("🇧🇩 AI Study-Buddy")
st.caption("Developed by Sagar | The nomadic programmer")

load_dotenv()

topic = st.text_input("আপনি কোন টপিকটি শিখতে চান?", placeholder="যেমন: Opportunity Cost বা Newton's Law")

if st.button("নোট তৈরি করো "):
    if not topic:
        st.warning("দয়া করে একটি টপিক লিখুন!")
    else:
        with st.spinner(f"'{topic}' নিয়ে গবেষণা চলছে... একটু অপেক্ষা করুন..."):
            try:
                tools = [TavilySearchResults(max_results=3)]
                
                llm = ChatGoogleGenerativeAI(
                    model="gemini-2.0-flash", 
                    temperature=0.4
                )
                
                agent_executor = create_react_agent(llm, tools)

                query = f"""
                You are an expert teacher explaining complex topics to Bangladeshi students in simple Bangla.
                
                Topic: '{topic}'
                
                Create a study note in Bangla (Bengali) with:
                
                1. Simple Definition: Easy to understand.
                
                2. A Unique & Context-Aware Bangladeshi Example:
                   - STOP giving the same 'rickshaw' example.
                   - Choose the BEST matching scenario (Village, Urban, Market, Food, Sports, etc.).
                   - Make it fun and specific.

                3. Pros and Cons:
                   - MUST use a Markdown Table for this.
                
                IMPORTANT FORMATTING RULES:
                - Use standard Markdown syntax.
                - Do NOT use excessive hyphens (----) or try to draw borders.
                - Just use | Header | and |---| separators strictly.
                - Do NOT add a bottom border line.
                """

                response = agent_executor.invoke({"messages": [("user", query)]})
                
                raw_content = response["messages"][-1].content
                final_answer = ""
                if isinstance(raw_content, list):
                    for block in raw_content:
                        if isinstance(block, dict) and "text" in block:
                            final_answer += block["text"]
                        else:
                            final_answer += str(block)
                else:
                    final_answer = str(raw_content)

                st.success("নোট তৈরি সম্পন্ন!")
                st.markdown("---")
                st.markdown(final_answer)  
                st.markdown("---")
                
                html_content = markdown.markdown(final_answer, extensions=['tables'])
                html_template = f"""
                <html>
                <head><style>body{{font-family:'SolaimanLipi', sans-serif; padding:20px;}} table{{border-collapse:collapse; width:100%;}} th,td{{border:1px solid #ddd; padding:8px;}} th{{background-color:#006a4e; color:white;}}</style></head>
                <body>
                <h1 style="text-align:center; color:#006a4e;">{topic}</h1>
                {html_content}
                <br><center><small>Generated by AI Study Buddy</small></center>
                </body>
                </html>
                """
                st.download_button(
                    label="নোটটি ডাউনলোড করুন (HTML)",
                    data=html_template,
                    file_name=f"{topic}.html",
                    mime="text/html"
                )

            except Exception as e:
                st.error(f"একটি সমস্যা হয়েছে: {e}")